title: My Personal Conference Deadlines
description: Countdowns to personal conference deadline targets
author: Peter Henderson

domain: "breakend.github.io"
baseurl: "https://breakend.github.io/ai-deadlines"

twitter_username: astro_pyotr
twitter_hashtag: machinelearning
github_username: Breakend
github_repo: ai-deadlines

markdown: kramdown
ga_id: 

include: ['_pages']